CREATE DATABASE quan_ly_diem_thi;
USE quan_ly_diem_thi;
DROP DATABASE quan_ly_diem_thi;
CREATE TABLE student(
maHS VARCHAR(20) PRIMARY KEY,
tenHS VARCHAR(50),
birthday date,
lop VARCHAR(20),
GT VARCHAR(20)
);

CREATE TABLE monHoc(
maMH VARCHAR(20) PRIMARY KEY,
tenMH VARCHAR(50)
);

CREATE TABLE bangDiem(
maHS VARCHAR(20),
maMH VARCHAR(20),
diemThi INT,
ngayKT DATETIME,
PRIMARY KEY (MaHS, MaMH),
FOREIGN KEY (MaHS) REFERENCES student(maHS),
FOREIGN KEY (MaMH) REFERENCES monHoc(maMH)
);

CREATE TABLE giaoVien(
    maGV VARCHAR(20) PRIMARY KEY,
    tenGV VARCHAR(20),
    SDT VARCHAR(10)
);

ALTER TABLE monHoc ADD maGV VARCHAR(20);
ALTER TABLE monHoc ADD CONSTRAINT FK_maGV FOREIGN KEY (maGV) REFERENCES giaoVien(maGV);
